# Generated by Django 3.1.5 on 2021-01-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('square', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('ownerName', models.CharField(max_length=128)),
                ('ownerContact', models.CharField(max_length=256)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
    ]
